name: Run Daily Weather Data

on:
  schedule:
     # Execute the workflow daily at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:  # Enable manual execution of the workflow

permissions:
  contents: write # Allow modifications to repository content

jobs:
  run-weather:
    runs-on: ubuntu-latest  # Execute on the latest Ubuntu virtual machine

    steps:
    # Step 1: Retrieve the repository contents
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Configure the Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Step 3: Install bash and wget tools
    - name: Set up bash and wget
      run: sudo apt-get update && sudo apt-get install -y wget

    # Step 4: Execute the weather data script
    - name: Run weather script
      run: bash weather.sh  # Use bash to execute the script

    # Step 5: Save and upload the updated weather data
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Stage the updated weather data
        git add data/weather/*.json
        
        # Commit changes if there are any
        git commit -m "Update weather data for $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        
        # Push the changes to the main branch
        git push origin main