name: Daily Weather Update

on:
  schedule:
    # Run every day at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows the workflow to be triggered manually if necessary

permissions:
  contents: write # Allows the workflow to update repository content

jobs:
  collect-weather:
    runs-on: ubuntu-latest # Specify Ubuntu as the virtual machine environment

    steps:
    # Step to clone the repository contents
    - name: Clone repository files
      uses: actions/checkout@v3

    # Install required dependencies (e.g., wget for downloading files)
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y wget

    # Ensure the weather.sh script is executable before running
    - name: Make weather.sh executable
      run: chmod +x weather.sh

    # Stop the workflow from running after a defined end date
    - name: Validate workflow execution date
      run: |
        current_date=$(date +'%Y-%m-%d')
        deadline="2024-12-31"
        if [[ "$current_date" > "$deadline" ]]; then
          echo "The date $current_date has passed the set deadline $deadl
git