name: Daily Weather Update

on:
  schedule:
    # Executes at 10:00 AM UTC daily
    - cron: '0 10 * * *'
  workflow_dispatch: # Enables manual execution if needed

permissions:
  contents: write # Required for pushing changes to the repository

jobs:
  collect-weather:
    runs-on: ubuntu-latest # Use a Linux virtual machine for execution

    steps:
    # Pull the repository files
    - name: Clone repository
      uses: actions/checkout@v3

    # Prepare environment with necessary tools
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget

    # Grant execution permissions to weather.sh
    - name: Set execute permissions
      run: chmod +x weather.sh

    # Prevent execution after a specific date
    - name: Ensure workflow stops post-2024
      run: |
        today=$(date +'%Y-%m-%d')
        cutoff="2024-12-31"
        if [[ "$today" > "$cutoff" ]]; then
          echo "Date $today exceeds $cutoff. Workflow will not proceed."
          exit 0
        fi

    # Execute the weather data script
    - name: Execute weather retrieval
      run: ./weather.sh

    # Track changes in weather data files
    - name: Commit and synchronize changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Automated Runner"
        git config --global user.email "runner@github.com"

        # Fetch the latest updates from the repository
        git fetch origin main

        # Verify if new data exists
        if git diff --quiet data/weather/*.json; then
          echo "No updates detected in weather data."
          exit 0
        fi

        # Stage, commit, and push changes
        git add data/weather/*.json
        git commit -m "Weather data update: $(date +'%Y-%m-%d %H:%M:%S')"

        # Synchronize with remote to prevent conflicts
        git pull origin main --rebase
        git push origin main
