name: Daily Weather Fetch

on:
  schedule:
    # Run at 9:59 AM UTC every day
    - cron: '59 9 * * *'
  workflow_dispatch:  # Allow manual execution of the workflow

permissions:
  contents: write  # Enable write permissions for pushing updates

jobs:
  fetch-weather-data:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Clone Repository
        uses: actions/checkout@v3

      # Step 2: Configure Python Environment
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install Required Tools
      - name: Install Utilities
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y wget

      # Step 4: Execute the Weather Script
      - name: Execute Weather Script
        run: bash scripts/fetch_weather.sh

      # Step 5: Commit and Push Changes
      - name: Update Weather Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Automated Bot"
          git config --global user.email "bot@github.com"
          
          # Stage changes
          git add data/weather/*.json
          
          # Commit updates if changes exist
          git commit -m "Weather Data Update: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit."
          
          # Push to main branch
          git push origin main